### ISSUE TITLE
Update for firefox quantum.

### ISSUE THREAD

**Issue by ghost** [schomery/speedyfox#10]
This extension no longer works on the latest version of firefox. While there has been changes that make some options obsolete there are some new options worth optimizing for speed and convenience.

**Comment by localhorst** [comment]
+1 for an Update

**Comment by grahamperrin** [comment]
Maybe related: 

- Mozilla bug [1363856 - [tracker] Implement WebExtensions API to give access to specific preferences](https://bugzilla.mozilla.org/show_bug.cgi?id=1363856)

**Comment by ghost** [comment]
the speedyfox project seems to be dead. I am closing the issue for now.
