### ISSUE TITLE
2 minor bugs

### ISSUE THREAD

**Issue by Garve** [schomery/speedyfox#2]
Hi!

1. In the addon options, it says 'spport' page.

2. The recommended value for network.dns.disablePrefetch should be FALSE and not TRUE.

Thanks for this addon btw!

**Comment by schomery** [comment]
Thanks

True is now recommended for `'network.dns.disablePrefetch`
False is now recommended for `network.prefetch-next`

**Comment by Smultie** [comment]
DisablePrefetch it set at TRUE while recommended is FALSE according to the text
Fast-fallback-to-IPv4 is set to FALSE while recommended it TRUE according to the text.

**Comment by schomery** [comment]
Thanks for the report. It is fixed on 0.1.5b1
https://github.com/schomery/speedyfox/blob/master/builds/jid1-wZqm19rJzRkZUA@jetpack-0.1.5b1.xpi?raw=true
