### ISSUE TITLE
Can't access option on Firefox for Android

### ISSUE THREAD

**Issue by sigdemo80** [schomery/speedyfox#4]
Since version 0.1.4 I can't access option on my phone and tablet.

If it helps the word "option" briefly appear when I activate/desactivate extension.

Thanks

**Comment by jawz101** [comment]
I don't even see option come up

**Comment by schomery** [comment]
Seems like this is an internal bug, https://bugzilla.mozilla.org/show_bug.cgi?id=1038003

This should be fixed soon. Unfortunately there is no easy way to open options page on Fennic from addon itself.

**Comment by sigdemo80** [comment]
I guess we just have to wait for a Firefox update then.

Thanks for this addon and I'll close this issue as soon as it will be fixed by Mozilla.

**Comment by FlyingHorseGA** [comment]
I see the same problem...

**Comment by sigdemo80** [comment]
Version 45 doesn't fix the problem

**Comment by Grossdm** [comment]
I also have this problem.
"Plus One" for me too...
😆

**Comment by schomery** [comment]
Finally this issue is fixed on version 0.1.7.
https://addons.mozilla.org/en-US/firefox/addon/speed-tweaks-speedyfox/versions

**Comment by simonbcn** [comment]
Please reopen this issue. Firefox 52.0.2 has same problem. 
It would be better put an option in menu.
