### ISSUE TITLE
network.http.speculative-parallel-limit Not

### ISSUE THREAD

**Issue by dallas7** [schomery/speedyfox#5]
Thank you for developing Speed Tweaks.
Windows 7 HP SP1 x64 - Cyberfox Intel X64 Portable 44.0.2
With 0.1.4, the "network.http.speculative-parallel-limit" preference was not added to the list (if by the list you mean the extension's Options pane under about:addons) even after a restart.  Both "network.http.speculative-parallel-limit" and "extensions.jid1-wZqm19rJzRkZUA@jetpack.network.http.speculative-parallel-limit" exist under about:config, both with the value of 6. I've confirmed jid1-wZqm19rJzRkZUA is your xpi on my system.
I have two network.http.redirection-limit in the Options pane and when I change the 2nd (lower) one from 6 to 0, both those two prefs above go to 0.  The 1st (upper) remains at 20 for both about:config prefs.
Looks like that 2nd network.http.redirection-limit is wrong.

**Comment by schomery** [comment]
Thanks for the report. It is now fixed on the latest dev version
https://github.com/schomery/speedyfox/blob/master/builds/jid1-wZqm19rJzRkZUA@jetpack-0.1.5b1.xpi?raw=true
