### ISSUE TITLE
[Suggestion] Move buttons with Set to recommended and Reset to the top

### ISSUE THREAD

**Issue by damat** [schomery/speedyfox#7]
https://dl.dropboxusercontent.com/s/0rixsyf8q9pkpy3/shot_160908_115159.png

This should be on top =) I have set to recommend all settings first, and only after that found those buttons =)

Also it would be great to have visual indicator if value differs from recommended.

**Comment by schomery** [comment]
Thanks for the feedback. We will have these two on top on the next release.

> Also it would be great to have visual indicator if value differs from recommended.

We are using prefs window and as far as I know it is not possible to stlye settings. I'll check one more time though.

**Comment by damat** [comment]
You are awesome! Thanks!
