### ISSUE TITLE
network.http.pipelining.maxrequests recommended value is invalid

### ISSUE THREAD

**Issue by jawz101** [schomery/speedyfox#8]
http://kb.mozillazine.org/Network.http.pipelining.maxrequests

The only valid values are 1 thru 8.  My current default in Firefox for Android is 6.  Any value higher than 8 defaults to 8.

I don't see the point in adjusting it to a higher value if a higher value than 8 is just recognized as an 8.  Because the current default is 6 why even change it and, even so, put it at a value which isn't even a valid value?

I'm all for tweaks but it should reflect legitimate values, nonetheless.

**Comment by schomery** [comment]
This documentation needs revision. `network.http.pipelining.maxrequests` can now be set to 32 as well. In fact the default value is 32. We are also going to recommend 32. Thanks for the report.

**Comment by jawz101** [comment]
How are you finding that out?  The about:config screen bugs me.  No documentation, will accept invalid values.  Doesn't distinguish between which OS's each is compatible with... bugs me.

**Comment by schomery** [comment]
https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js#1470-1471

**Comment by jawz101** [comment]
awesome.  Thanks.  I've been curious about digging into config settings.  It's such a screwy implementation.
